Enabled: 

SCServer: 127.0.0.1:25500
SCServerRemote: api.wcc.best
Git:
  email: <Your Git's email>
  name: <Your Git's name>
ProxyProviders:
#  <P1>: <URL1>
#  <P2>: <URL2>
#  ...
ClashProviders:
  target: clash
  list: true
#  udp: true
#  emoji: true
#  sort: true
QuantumultXRemotes: 
  target: quanx
  list: true
# ...
#ExcludeExp: 
#  syntax: 奈飞小铺|过期时间|剩余流量|官网
#  whitelist: 
#  - <P2>
#  - ...
# QuickGenQX: true
SmartFilter: 
# - <P1>
# - ...