name: Update Provider

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
      branches:
          - NPO
  schedule:
      - cron: '20 12,18 * * *'
  watch:
      types: 
          - started

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  UpdateProviders:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Download Providers
      run: bash update.sh
    - name: Commit files
      run: |
        git config --local user.email "felicia@realnet.ml"
        git config --local user.name "FeliciaWen"
        git add -A
        git commit -m "Update Proxy Provider." -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

